name: Update README

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # ⭐ 這行就是你要加的
      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: |
          python SCRIPTS/update_problems.py
          python SCRIPTS/update_topics.py
          python SCRIPTS/update_progress.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add README.md
          git commit -m "auto update README" || echo "no changes"
          git push
